"""Unique no apikey do weather station

Revision ID: 9d1059f6ea03
Revises: c91607299bd1
Create Date: 2022-10-08 21:04:57.061807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1059f6ea03'
down_revision = 'c91607299bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weatherstation_api_key', table_name='weatherstation')
    op.create_index(op.f('ix_weatherstation_api_key'), 'weatherstation', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weatherstation_api_key'), table_name='weatherstation')
    op.create_index('ix_weatherstation_api_key', 'weatherstation', ['api_key'], unique=False)
    # ### end Alembic commands ###
