"""First version

Revision ID: c91607299bd1
Revises: 
Create Date: 2022-10-08 19:09:03.367821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91607299bd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weatherstation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('altitude', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weatherstation_api_key'), 'weatherstation', ['api_key'], unique=False)
    op.create_index(op.f('ix_weatherstation_city'), 'weatherstation', ['city'], unique=False)
    op.create_index(op.f('ix_weatherstation_country'), 'weatherstation', ['country'], unique=False)
    op.create_index(op.f('ix_weatherstation_id'), 'weatherstation', ['id'], unique=False)
    op.create_index(op.f('ix_weatherstation_name'), 'weatherstation', ['name'], unique=False)
    op.create_table('weatherrecord',
    sa.Column('weather_station_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('heat_index', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dewpoint', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pressure', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dioxide_carbon_ppm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rain_presence', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['weather_station_id'], ['weatherstation.id'], ),
    sa.PrimaryKeyConstraint('weather_station_id', 'date')
    )
    op.create_index(op.f('ix_weatherrecord_date'), 'weatherrecord', ['date'], unique=False)
    op.create_index(op.f('ix_weatherrecord_weather_station_id'), 'weatherrecord', ['weather_station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weatherrecord_weather_station_id'), table_name='weatherrecord')
    op.drop_index(op.f('ix_weatherrecord_date'), table_name='weatherrecord')
    op.drop_table('weatherrecord')
    op.drop_index(op.f('ix_weatherstation_name'), table_name='weatherstation')
    op.drop_index(op.f('ix_weatherstation_id'), table_name='weatherstation')
    op.drop_index(op.f('ix_weatherstation_country'), table_name='weatherstation')
    op.drop_index(op.f('ix_weatherstation_city'), table_name='weatherstation')
    op.drop_index(op.f('ix_weatherstation_api_key'), table_name='weatherstation')
    op.drop_table('weatherstation')
    # ### end Alembic commands ###
